<a href="https://colab.research.google.com/github/ejekanshjain/easy-hacktoberfest/blob/main/BioSymphony_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Assignment 1
# Add 10 numbers using functions in Python Programming. Func1() will take 10
# arguments in the form of 10 numbers and print the summation result. Accordingly,
# Func2() will take 10 numbers by using the concept of reference variable or keyword
# arguments and simultaneously add those. Compute the time constraints of these two
# functions.

import time

# Function to add 10 numbers using positional arguments
def Func1(num1, num2, num3, num4, num5, num6, num7, num8, num9, num10):
    start_time = time.time()
    result = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10
    end_time = time.time()
    print("Sum using positional arguments:", result)
    print("Time taken for Func1:", end_time - start_time, "seconds")

# Function to add 10 numbers using keyword arguments
def Func2(**kwargs):
    start_time = time.time()
    result = sum(kwargs.values())
    end_time = time.time()
    print("Sum using keyword arguments:", result)
    print("Time taken for Func2:", end_time - start_time, "seconds")

numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

Func1(*numbers)
Func2(num1=1, num2=2, num3=3, num4=4, num5=5, num6=6, num7=7, num8=8, num9=9, num10=10)


Sum using positional arguments: 55
Time taken for Func1: 9.5367431640625e-07 seconds
Sum using keyword arguments: 55
Time taken for Func2: 2.1457672119140625e-06 seconds


In [ ]:
# Assignment 2
# Create a 3x3 matrix and perform LU factorization.

import numpy as np
import scipy.linalg as la

A = np.array([[4, 3, 2],
              [9, 7, 8],
              [1, 5, 6]])

P, L, U = la.lu(A)

print("Original Matrix A:")
print(A)

print("Permutation Matrix P:")
print(P)

print("Lower Triangular Matrix L:")
print(L)

print("Upper Triangular Matrix U:")
print(U)


Original Matrix A:
[[4 3 2]
 [9 7 8]
 [1 5 6]]
Permutation Matrix P:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Lower Triangular Matrix L:
[[ 1.          0.          0.        ]
 [ 0.11111111  1.          0.        ]
 [ 0.44444444 -0.02631579  1.        ]]
Upper Triangular Matrix U:
[[ 9.          7.          8.        ]
 [ 0.          4.22222222  5.11111111]
 [ 0.          0.         -1.42105263]]


In [ ]:
# Assignment 3
# Create one-dimensional, two-dimensional, and three-dimensional arrays using Numpy
# module and accordingly compute the speed of different arrays.

import numpy as np
import time

# 1-dimensional array
one_dimensional_array = np.random.rand(1000000)

# 2-dimensional array
two_dimensional_array = np.random.rand(1000, 1000)

# 3-dimensional array
three_dimensional_array = np.random.rand(100, 100, 100)

# Measure the speed of each array creation
start_time = time.time()
_ = np.random.rand(1000000)
one_dimensional_time = time.time() - start_time

start_time = time.time()
_ = np.random.rand(1000, 1000)
two_dimensional_time = time.time() - start_time

start_time = time.time()
_ = np.random.rand(100, 100, 100)
three_dimensional_time = time.time() - start_time

print("Time taken to create 1-dimensional array: {:.6f} seconds".format(one_dimensional_time))
print("Time taken to create 2-dimensional array: {:.6f} seconds".format(two_dimensional_time))
print("Time taken to create 3-dimensional array: {:.6f} seconds".format(three_dimensional_time))


Time taken to create 1-dimensional array: 0.019038 seconds
Time taken to create 2-dimensional array: 0.019151 seconds
Time taken to create 3-dimensional array: 0.019257 seconds


In [ ]:
# Assignment 4
# What is the sparsity of a matrix? Create a sparse matrix and find the sparsity of the matrix.

# The sparsity of a matrix is a measure of how many of its elements are zero or
# empty relative to the total number of elements. In other words,
# it indicates the proportion of zero elements in a matrix.
# A matrix is considered sparse when a significant portion of its entries is zero.

import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse import find

dense_matrix = np.array([[0, 0, 0, 0, 0],
                        [0, 0, 5, 0, 0],
                        [0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0]])

sparse_matrix = csr_matrix(dense_matrix)

non_zero_elements = find(sparse_matrix)

total_elements = sparse_matrix.shape[0] * sparse_matrix.shape[1]
sparsity = 1 - (len(non_zero_elements[0]) / total_elements)

print("Sparse Matrix:")
print(sparse_matrix.toarray())
print("Sparsity of the matrix: {:.4f}".format(sparsity))


Sparse Matrix:
[[0 0 0 0 0]
 [0 0 5 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Sparsity of the matrix: 0.9500


In [ ]:
# Assignment 5
# Create a dataframe and compute the mean, median, and S.D. of the data. Apply MinMaxScaling
# technique to compute each and every rows of Salary column.
# MinMaxScaling formula = (data(salary) – minimum of data(salary))/(maximum of data(salary)-minimum of data (salary))

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = {'Id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'Age': [32, 21, 54, 34, 87, 43, 28, 59, 45, 47],
        'Salary': [10000, 15000, 20000, 24000, 57000, 45000, 87000, 31000, 35000, 65000]}

df = pd.DataFrame(data)

mean_salary = df['Salary'].mean()
median_salary = df['Salary'].median()
std_dev_salary = df['Salary'].std()

print(f"Mean Salary: {mean_salary}")
print(f"Median Salary: {median_salary}")
print(f"Standard Deviation of Salary: {std_dev_salary}")

scaler = MinMaxScaler()
df['Scaled_Salary'] = scaler.fit_transform(df[['Salary']])

print(df)


Mean Salary: 38900.0
Median Salary: 33000.0
Standard Deviation of Salary: 24546.780734842694
   Id  Age  Salary  Scaled_Salary
0   1   32   10000       0.000000
1   2   21   15000       0.064935
2   3   54   20000       0.129870
3   4   34   24000       0.181818
4   5   87   57000       0.610390
5   6   43   45000       0.454545
6   7   28   87000       1.000000
7   8   59   31000       0.272727
8   9   45   35000       0.324675
9  10   47   65000       0.714286


In [ ]:
# Assignment 6
# F(x)=x^2 within an interval [0,1]. What would be the value for definite integral?

from scipy import integrate

def f(x):
    return x**2

result, _ = integrate.quad(f, 0, 1)

print("Definite Integral:", result)


Definite Integral: 0.33333333333333337


In [ ]:
# Assignment 7
# X = [2,4,5,9,14], and y = [3.5,4.1,5.2,9.1,17],,, find the slope and intercept values
# after computing linear regression using scipy module.


import numpy as np
from scipy import stats

X = [2, 4, 5, 9, 14]
y = [3.5, 4.1, 5.2, 9.1, 17]

slope, intercept, r_value, p_value, std_err = stats.linregress(X, y)

print("Slope:", slope)
print("Intercept:", intercept)


Slope: 1.1539647577092513
Intercept: -0.06696035242290943


In [ ]:
# Assignment 8
# What is the difference between list and arrays?

# In Python, both lists and arrays are used to store collections of data. However, there are some key differences between the two:

# Data Type:
# Lists: In Python, lists are a versatile data structure that can store elements of different data types. You can have a list that contains integers, strings, floats, or even other lists.
# Arrays: Arrays in Python typically refer to arrays created using external libraries like NumPy. These arrays are designed to work with homogeneous data types, which means that all elements in the array should be of the same data type (e.g., all integers or all floats). This homogeneity allows for more efficient memory usage and faster operations on the data.

# Performance:
# Lists: Lists are more flexible but are generally slower than arrays because they are not optimized for mathematical or numerical operations.
# Arrays: Arrays, especially NumPy arrays, are highly optimized for numerical computations. They provide a significant performance advantage over lists when performing operations on large datasets.

# Size Flexibility:
# Lists: Lists in Python can dynamically change in size. You can add or remove elements as needed.
# Arrays: Arrays created with libraries like NumPy have a fixed size upon creation. You cannot change the size of an array. If you need to change the size, you have to create a new array.

# Functionality:
# Lists: Lists offer a wide range of built-in functions and methods for common operations like appending, extending, slicing, and more. They are suitable for general-purpose data storage.
# Arrays: NumPy arrays offer a comprehensive set of functions for performing mathematical and statistical operations. They are widely used in scientific computing, data analysis, and machine learning.



# Here's a brief example illustrating the difference:

# Using a List:

my_list = [1, 2, 3, 4, 5]
print(my_list)

# Using a NumPy Array:

import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
# Assignment 9
# Two sets are present. Set A is consisting = {1,2,3,4,5}, and set B is consisting =
# {4,5,6,7,8}. Now figure out the intersection points, and A-B from these two sets.

set_A = {1, 2, 3, 4, 5}
set_B = {4, 5, 6, 7, 8}

intersection = set_A.intersection(set_B)

# Set difference A - B
difference_A_B = set_A - set_B

print("Intersection of A and B:", intersection)
print("Set Difference (A - B):", difference_A_B)


Intersection of A and B: {4, 5}
Set Difference (A - B): {1, 2, 3}


In [ ]:
# Assignment 10
# Define a square matrix and find out the eigenvalues and eigenvectors.

import numpy as np

A = np.array([[4, -2],
              [1,  1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
# Assignment 11
# What do you mean by dimensionality reduction? Create a 10x10 matrix and reduce
# the dimensions of the matrix where components would be 5 and print the value.

# Dimensionality reduction is a technique used in data analysis and machine learning to reduce the number of features or dimensions in a dataset while preserving as much meaningful information as possible.
# Principal Component Analysis (PCA) is a commonly used method for dimensionality reduction.

import numpy as np
from sklearn.decomposition import PCA

matrix = np.random.rand(10, 10)

pca = PCA(n_components=5)

reduced_matrix = pca.fit_transform(matrix)

print(reduced_matrix)


[[-0.24076676  0.49950705 -0.2138323   0.65798433 -0.3184592 ]
 [ 0.28547518 -0.31725911 -0.10675694 -0.43047485 -0.35801848]
 [-0.22265574  0.7378206   0.42767185 -0.36928168 -0.28062547]
 [ 0.06321022 -0.54871029 -0.25676322  0.00781662 -0.36360136]
 [-0.79241992 -0.49173166  0.27883216  0.01016375  0.06979588]
 [ 0.23002268 -0.11294044  0.68658167  0.06327412  0.24217713]
 [-0.38654504  0.20889913 -0.60921152 -0.3265318   0.32944247]
 [-0.31387454 -0.2295772  -0.00791138  0.32204962  0.23220898]
 [ 1.10458157 -0.01746372 -0.03641921  0.17942815  0.07674424]
 [ 0.27297235  0.27145565 -0.1621911  -0.11442826  0.37033581]]


In [ ]:
# Assignment 12
# Get the mean covariance from the above dataset without using any inbuilt functions.
# Find out the correlation matrix of the dataset.

# Define the dataset
X = [100, 150, 410, 105, 450, 720, 735, 801, 987, 441]
Y = [855, 780, 444, 673, 785, 109, 175, 193, 1020, 78]

# Calculate the mean of X and Y
mean_X = sum(X) / len(X)
mean_Y = sum(Y) / len(Y)

# Calculate the covariance
n = len(X)
covariance = sum((X[i] - mean_X) * (Y[i] - mean_Y) for i in range(n)) / (n - 1)

# Calculate the correlation matrix
# Create a 2x2 matrix for correlation
correlation_matrix = [[0, 0], [0, 0]]

# Calculate the diagonal values (variance of X and Y)
variance_X = sum((x - mean_X) ** 2 for x in X) / (n - 1)
variance_Y = sum((y - mean_Y) ** 2 for y in Y) / (n - 1)
correlation_matrix[0][0] = variance_X
correlation_matrix[1][1] = variance_Y

# Calculate the off-diagonal value (correlation between X and Y)
correlation_matrix[0][1] = covariance / ((variance_X * variance_Y) ** 0.5)
correlation_matrix[1][0] = correlation_matrix[0][1]

print("Mean Covariance:", covariance)
print("Correlation Matrix:")
for row in correlation_matrix:
    print(row)


Mean Covariance: -32564.200000000004
Correlation Matrix:
[98108.9888888889, -0.2948835367856574]
[-0.2948835367856574, 124299.95555555554]
